name = "EbmCommon"
uuid = "f104a7c3-3688-4e7c-9c13-313faccad043"
version = "0.7.2"
authors = ["Hung Nguyen Duc <ndgnuh@protonmail.com>"]

[workspace]
projects = ["example"]

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
BifurcationKit = "0f109fa4-8a5d-4b75-95aa-f515264e7665"
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
RequiredInterfaces = "97f35ef4-7bc5-4ec1-a41a-dcc69c7308c6"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[compat]
Accessors = "0.1.42"
BifurcationKit = "0.5.3"
Chain = "^0.6.0"
Compat = "4.18.0"
DiffEqCallbacks = "4.9.0"
DocStringExtensions = "0.9.4"
MacroTools = "0.5.16"
Makie = "^0.24.0"
OrdinaryDiffEqTsit5 = "1.1.0"
Polynomials = "4.0.21"
Reexport = "1.2.2"
RequiredInterfaces = "0.1.7"
ReverseDiff = "1.16.1"
StaticArrays = "1.9.15"
StructTypes = "1.11.0"
UnPack = "1.0.2"
